public enum MessageType
{
	SOCKET_CLOSED,
    AFTER_LOGIN_SCENE_CHANGE,
    AFTER_LOGIN_FAILED,
    AFTER_CREATE_ACCOUNT_SUCCESS,
    AFTER_CREATE_ACCOUNT_FAILED,

    AFTER_RECV_CHANNEL_LIST,

    AFTER_ENTER_CHANNEL_SUCCESS,
    AFTER_ENTER_CHANNEL_FAILED,

    SCENE_CHANGE_LOGIN_TO_LOBBY,
    SCENE_CHANGE_LOBBY_TO_WORLD,

    RES_PLAYER_ENTER,

    UPDATE_FORECAST_INFO,
    UPDATE_FORECAST_HUD_INFO,
    UPDATE_USER_POSITION,

    NOTIFY_PLAYER_ENTER,
    NOTIFY_PLAYER_EXIT,
    NOTIFY_PLAYER_MOVE,

    NOTIFY_GAME_START,
    NOTIFY_PLAYER_ROOM_ENTER,
    NOTIFY_PLAYER_ROOM_EXIT,
    NOTIFY_PLAYER_ROOM_READY,
    NOTIFY_ROOM_SET_TYPE,
    NOTIFY_PLAYER_SET_HOST,
    RES_GAME_START,
    RES_CREATE_ROOM_INFO,
    RES_ROOM_INFO,
    RES_ROOM_MAKE,
    RES_ROOM_PLAYER_ENTER,
    RES_ROOM_PLAYER_EXIT,

    GAMEROOM_START,
    INGAME_START,
    INGAME_END,
    INGAME_PLAYER_ADD,
    INGAME_POSITION_UPDATE,
    NOTIFY_TRACK_COUNT_UPDATE,
    NOTIFY_READY_COUNT,
    NOTIFY_PLAYER_TRACK_FINISHED,
    SCENE_CHANGE_TRACKGAME_TO_WORLD,

    GET_MY_REPLAY_DATA,
    GET_MY_RECORD_DATA,
}